### ISSUE TITLE
What is the current release structure for each product?

### ISSUE THREAD

**Issue by LizGrauel** [LizGrauel/GCIpm#11]
**Questions to answer**
- [ ] What types of releases do you have for each product?
- [ ] How frequent are releases for each product?
- [ ] Who decides that a release can be moved to production?
- [ ] Who is involved in each release?

**Comment by karljgeisler** [comment]
We try to aim for monthly releases for each product/client.  I make the decision (along w/ our creative team if they give the ok).

Damien handles releases and posts the updated code to AWS, and updates the servers.

**Comment by LizGrauel** [comment]
Ok great. Do you have the dates of the last 3 or 4 releases for each product? I'm just organizing past timelines to see if I can find trends

**Comment by karljgeisler** [comment]
Was back in early May (and before that was a release for each month).  We have been going through a large refresh over the summer, so have held off any releases until we get done.  My hope is that starting in September we will get back to a monthly release.  We do freeze November and December due to holidays, so we make no updates at that time.  However, starting January 15th, we will get back to monthly
